# Generated by Django 2.1.3 on 2018-12-01 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('chip', models.IntegerField(null=True)),
                ('adoption_day', models.DateField()),
                ('species', models.CharField(max_length=45)),
                ('breed', models.CharField(max_length=45)),
                ('color', models.CharField(max_length=45)),
                ('sex', models.CharField(max_length=45)),
                ('castrating', models.BooleanField()),
                ('pedigree', models.CharField(max_length=45)),
                ('tattoo', models.CharField(max_length=45, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Antiparasitic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examination_date', models.DateField()),
                ('diagnostic', models.TextField()),
                ('treatment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.Animal')),
            ],
        ),
        migrations.CreateModel(
            name='Deworming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateField()),
                ('reapplication_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('antiparasitic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.Antiparasitic')),
                ('clinical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.ClinicalRecord')),
            ],
        ),
        migrations.CreateModel(
            name='Inmunization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.IntegerField()),
                ('application_date', models.DateField()),
                ('reapplication_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.ClinicalRecord')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('create_at', models.DateField(auto_now=True)),
                ('street', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('colony', models.CharField(max_length=45)),
                ('state', models.CharField(max_length=45)),
                ('country', models.CharField(max_length=45)),
                ('zip_code', models.IntegerField()),
                ('phone', models.CharField(max_length=45)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserVet',
            fields=[
                ('cedula_profesional', models.IntegerField()),
                ('clinic_name', models.CharField(max_length=45)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='inmunization',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.Vaccine'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='antiparasitic',
            field=models.ManyToManyField(through='animals.Deworming', to='animals.Antiparasitic'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='vaccines',
            field=models.ManyToManyField(through='animals.Inmunization', to='animals.Vaccine'),
        ),
        migrations.AddField(
            model_name='animal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
