# Generated by Django 2.1.3 on 2018-11-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('chip', models.IntegerField(unique=True)),
                ('adoption_day', models.DateField()),
                ('species', models.CharField(max_length=45)),
                ('breed', models.CharField(max_length=45)),
                ('color', models.CharField(max_length=45)),
                ('sex', models.CharField(max_length=45)),
                ('pedigree', models.CharField(max_length=45)),
                ('tattoo', models.CharField(max_length=45, unique=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('modifed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
