# Generated by Django 2.1.3 on 2018-12-06 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='dead',
            field=models.BooleanField(null=True),
        ),
    ]
