# Generated by Django 2.1.3 on 2018-12-08 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_animal_dead'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='vets',
            field=models.ManyToManyField(to='animals.UserVet'),
        ),
    ]
